name: releases-api
services:
- name: releases-api
  github:
    branch: master
    deploy_on_push: true
    repo: alda-lang/releases-api
  dockerfile_path: Dockerfile
  # run_command: |
  #   cd /root/releases-api
  #   clj -M:serve 8080
  health_check:
    http_path: /
