name: releases-api
services:
- name: releases-api
  github:
    branch: master
    deploy_on_push: true
    repo: alda-lang/releases-api
  dockerfile_path: Dockerfile
  health_check:
    http_path: /health
