name: alda-api
services:
- name: alda-api
  github:
    branch: master
    deploy_on_push: true
    repo: alda-lang/alda-api
  dockerfile_path: Dockerfile
  health_check:
    http_path: /health
    initial_delay_seconds: 300
    period_seconds: 5
    timeout_seconds: 5
    success_threshold: 3
    failure_threshold: 9
